baseURL = "https://artistas.io/"
languageCode = "en-us"
title = "Artistas"
theme = "hugo-nuo"
publishDir = "docs"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[params]
  author = "fernandobandeira"
  github = "artistas"
  avatar = "/avatar.jpg"